create table funcionarios as select * from hr.employees;
create table departamentos as select * from hr.departments;

CREATE OR REPLACE FUNCTION GET_NAME (EMP_ID IN funcionarios.EMPLOYEE_ID%TYPE) 
RETURN VARCHAR2 IS 
	NOME VARCHAR2(100);
BEGIN 
	SELECT FIRST_NAME || ' ' || LAST_NAME INTO NOME
    FROM FUNCIONARIOS
    WHERE funcionarios.EMPLOYEE_ID = EMP_ID;
 
	RETURN NOME;

END GET_NAME; 
/

CREATE OR REPLACE FUNCTION GET_SALARY (EMP_ID IN funcionarios.EMPLOYEE_ID%TYPE) 
RETURN VARCHAR2 IS 
	SAL FUNCIONARIOS.SALARY%TYPE;
BEGIN 
	SELECT SALARY INTO SAL
    FROM FUNCIONARIOS
    WHERE funcionarios.EMPLOYEE_ID = EMP_ID;
 
	RETURN SAL;

END GET_SALARY; 
/


BEGIN 
    DBMS_OUTPUT.PUT_LINE('SALARIO: ' || GET_SALARY(123)));


INSERT INTO FUNCIONARIOS (EMPLOYEE_ID, FIRST_NAME, LAST_NAME) 
VALUES(1, 'jONH', 'LEMON');


CREATE OR REPLACE FUNCTION FUNC_DEPT (DEPT_ID IN NUMBER) 
RETURN VARCHAR2 IS 
	EMP_FIRST_NAME
    EMP_LAST_NAME EMPLOYEES
    DEPT_NAME HR.DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN 
	SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME INTO EMP_FIRST_NAME, EMP_LAST_NAME, DEPT_NAME
    FROM HR.EMPLOYEES JOIN HR.DEPARTMENTS
    ON HR.EMPLOYEES.DEPARTMENT_ID  = DEPT_ID
    WHERE 
 
	RETURN SAL;

END FUNC_DEPT; 



CREATE OR REPLACE FUNCTION GET_PAYMENT 
RETURN NUMBER IS
	V_FOLHA NUMBER;
BEGIN 
	SELECT SUM(SALARY) INTO V_FOLHA FROM EMPLOYEES;
	RETURN V_FOLHA;
END;

BEGIN 
	DBMS_OUTPUT.PUT_LINE(GET_PAYMENT);
END;


CREATE OR REPLACE FUNCTION GET_PAYMENT_WITH_ACS(DEPT_ID NUMBER)
RETURN NUMBER IS
	V_FOLHA NUMBER;
BEGIN 

    UPDATE EMPLOYEES 
    SET SALARY = SALARY * 1.1 
    WHERE DEPARTMENT_ID = DEPT_ID;
    	
	SELECT SUM(SALARY) INTO V_FOLHA 
    FROM EMPLOYEES;
	WHERE DEPARTMENT_ID = DEPT_ID;

	RETURN V_FOLHA;
END;

BEGIN 
	DBMS_OUTPUT.PUT_LINE(GET_PAYMENT_WITH_ACS(123));
END;

CREATE OR REPLACE PROCEDURE LIST_FUNC 
IS
CURSOR EMP_CUR IS 
SELECT DADOS

FROM FUNCIONARIOS
F
JOIN DEPARTAMENTOS D ON D.DEPARTMENT_ID = F.DEPARTMENT_ID
LEFT JOIN FUNCIONARIOS FU ON FU.EMPLOYEE_ID = F.MANAGER_ID;
BEGIN
FOR EMP_REC IN EMP_CUR LOOP
DBMS_OUTPUT.PUT_LINE(PRINTBONITINHO)
END LOOP;
END

