-- Questão 1
CREATE OR REPLACE VIEW V_EXPENSIVE_SUBPRODUCT AS
SELECT PROD_SUBCATEGORY, PROD_LIST_PRICE
FROM SH.PRODUCTS;

-- Questão 2
CREATE OR REPLACE VIEW V_MAX_CLIENT AS
SELECT c.CUSTOMER_NAME, SUM(s.SALE_AMOUNT) / COUNT(DISTINCT s.SALE_DATE) AS VALOR_MEDIO_COMPRAS
FROM SH.CUSTOMERS c
JOIN SH.SALES s ON c.CUSTOMER_ID = s.CUSTOMER_ID
WHERE s.SALE_DATE BETWEEN TO_DATE('1998-01-01', 'YYYY-MM-DD') AND TO_DATE('1998-12-31', 'YYYY-MM-DD')
GROUP BY c.CUSTOMER_NAME
HAVING SUM(s.SALE_AMOUNT) / COUNT(DISTINCT s.SALE_DATE) > (
    SELECT AVG(sub_total)
    FROM (
            SELECT SUM(SALE_AMOUNT) AS sub_total
            FROM SH.SALES
            WHERE SALE_DATE BETWEEN TO_DATE('1998-01-01', 'YYYY-MM-DD') AND TO_DATE('1998-12-31', 'YYYY-MM-DD')
            GROUP BY CUSTOMER_ID
        )
);

-- Questão 3
CREATE OR REPLACE VIEW V_EMP_DALLAS_CHICAGO AS
SELECT
    e.ENAME AS "Nome do Funcionário",
    e.JOB AS "Função",
    d.DNAME AS "Departamento",
    CASE
        WHEN e.COMM IS NOT NULL THEN e.SAL + e.COMM
        ELSE e.SAL
    END AS "Salário Total"
FROM SCOTT.EMP e
JOIN SCOTT.DEPT d ON e.DEPTNO = d.DEPTNO
WHERE d.LOC IN ('DALLAS', 'CHICAGO');


-- Questão 4
CREATE OR REPLACE VIEW V_FUNC_SALARY_GERENTE AS
SELECT FUNC.FIRST_NAME, FUNC.SALARY, MANAG.FIRST_NAME
FROM HR.EMPLOYEES FUNC INNER JOIN HR.EMPLOYEES MANAG
ON FUNC.MANAGER_ID = MANAG.EMPLOYEE_ID;

-- Questão 5
CREATE OR REPLACE VIEW V_EMP_LOC AS
	SELECT HR.EMPLOYEES.FIRST_NAME, HR.DEPARTMENTS.DEPARTMENT_NAME, HR.LOCATIONS.CITY 	
    FROM HR.EMPLOYEES 
    INNER JOIN HR.DEPARTMENTS 
    	ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
	INNER JOIN HR.LOCATIONS 
    	ON HR.LOCATIONS.LOCATION_ID = HR.DEPARTMENTS.LOCATION_ID;

-- Questão 6
CREATE OR REPLACE VIEW V_DEPT_NAME AS
	SELECT HR.EMPLOYEES.FIRST_NAME, HR.JOBS.JOB_TITLE, HR.DEPARTMENTS.DEPARTMENT_ID, HR.DEPARTMENTS.DEPARTMENT_NAME
	FROM HR.EMPLOYEES
	INNER JOIN HR.DEPARTMENTS 123
    	ON HR.DEPARTMENTS.DEPARTMENT_ID = HR.EMPLOYEES.DEPARTMENT_ID
	INNER JOIN HR.JOBS
		ON HR.JOBS.JOB_ID = HR.EMPLOYEES.JOB_ID    
    INNER JOIN HR.LOCATIONS
    	ON HR.DEPARTMENTS.LOCATION_ID = HR.LOCATIONS.LOCATION_ID 
	WHERE HR.LOCATIONS.CITY IN ('Tokyo', 'Roma', 'Oxford', 'Munich');

-- Questão 7
CREATE OR REPLACE VIEW V_EMP_MAN AS
	SELECT EMP.FIRST_NAME funcionario, EMP.EMPLOYEE_ID nr_funcionario, MAN.FIRST_NAME gerente, MAN.MANAGER_ID nr_gerente
    FROM HR.EMPLOYEES EMP INNER JOIN HR.EMPLOYEES MAN 
    ON  EMP.EMPLOYEE_ID = MAN.MANAGER_ID;

-- Questão 8
CREATE OR REPLACE VIEW V_DEP_MAN_NAME AS
	SELECT MAN.FIRST_NAME, D.DEPARTMENT_NAME, L.CITY
	FROM HR.EMPLOYEES EMP 
    INNER JOIN HR.EMPLOYEES MAN ON  EMP.EMPLOYEE_ID = MAN.MANAGER_ID
	INNER JOIN HR.DEPARTMENTS D ON D.DEPARTMENT_ID = MAN.DEPARTMENT_ID	
    INNER JOIN HR.LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;

-- Questão 9
CREATE OR REPLACE VIEW V_NAME_JOB AS
    SELECT FIRST_NAME, JOB_TITLE, SALARY
    FROM HR.EMPLOYEES EMP INNER JOIN HR.JOBS JOB
    ON EMP.JOB_ID = JOB.JOB_ID
    WHERE SALARY > 3850;

-- Questão 10
CREATE OR REPLACE VIEW V_NAME_AVG AS
    SELECT FIRST_NAME, SALARY 
    FROM HR.EMPLOYEES
    WHERE SALARY NOT BETWEEN 1500 AND 2850;

-- Questão 11
CREATE OR REPLACE VIEW V_DEPT AS
	SELECT HR.EMPLOYEES.SALARY SalarioMensal, HR.EMPLOYEES.FIRST_NAME Funcionario
    FROM HR.EMPLOYEES
	WHERE HR.EMPLOYEES.SALARY > 1500
    AND HR.EMPLOYEES.DEPARTMENT_ID IN (10, 30);

-- Questão 12
CREATE OR REPLACE VIEW V_MANAG AS
	SELECT HR.EMPLOYEES.FIRST_NAME, HR.JOBS.JOB_TITLE
    FROM HR.EMPLOYEES
    INNER JOIN HR.JOBS ON HR.JOBS.JOB_ID = HR.EMPLOYEES.JOB_ID
	WHERE HR.EMPLOYEES.MANAGER_ID IS NULL;

-- Questão 13
CREATE OR REPLACE VIEW V_COM AS
	SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.SALARY, NVL(EMPLOYEES.COMMISSION_PCT, 'não comissionado') AS COMMISSION_PCT 
    FROM HR.EMPLOYEES;

-- Questão 14
CREATE OR REPLACE VIEW V_NAME AS
    SELECT FIRST_NAME || ' ' || LAST_NAME AS FUNCIONARIO
    FROM HR.EMPLOYEES 
    WHERE (LOWER(FIRST_NAME) LIKE '%ss%' 
    OR LOWER(LAST_NAME) LIKE '%ss%' 
    AND DEPARTMENT_ID = 30) OR MANAGER_ID = 103;

-- Questão 15
CREATE OR REPLACE VIEW V_PROGRAMERS AS
	SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.SALARY, JOBS.JOB_TITLE 
    FROM HR.EMPLOYEES
    LEFT JOIN HR.JOBS ON JOBS.JOB_ID = EMPLOYEES.JOB_ID;

-- Questão 16
CREATE OR REPLACE VIEW V_SALARY AS
    SELECT DEPARTMENTS.DEPARTMENT_NAME, SUM(EMPLOYEES.SALARY) AS TOTAL_SALARY
    FROM HR.EMPLOYEES
    INNER JOIN HR.DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
    GROUP BY DEPARTMENTS.DEPARTMENT_NAME HAVING SUM(EMPLOYEES.SALARY) > 5000;

-- Questão 17
CREATE OR REPLACE VIEW V_FUNC_SAL AS  
    SELECT  JOBS.JOB_TITLE, MAX(EMPLOYEES.SALARY) AS "Mais alto por função"  
    FROM  HR.EMPLOYEES
    INNER JOIN HR.JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID 
    GROUP BY JOBS.JOB_TITLE
    HAVING MAX(EMPLOYEES.SALARY) <= 10000;

-- Questão 18
CREATE OR REPLACE VIEW V_AVG_SAL AS
    SELECT JOBS.JOB_TITLE, AVG(EMPLOYEES.SALARY) AS "Média de salário por função"
    FROM HR.EMPLOYEES
    INNER JOIN HR.JOBS 
    ON EMPLOYEES.JOB_ID = JOBS.JOB_ID
    WHERE OBS.JOB_TITLE LIKE '%Manager%'
    GROUP BY JOBS.JOB_TITLE;

-- Questão 19
CREATE OR REPLACE VIEW V_AVG_SAL_EMP AS
    SELECT JOBS.JOB_TITLE, AVG(EMPLOYEES.SALARY) AS "Média de salário por função"
    FROM HR.EMPLOYEES
    INNER JOIN HR.JOBS 
    ON EMPLOYEES.JOB_ID = JOBS.JOB_ID
    WHERE JOBS.JOB_TITLE LIKE '%Manager%'
    GROUP BY JOBS.JOB_TITLE
    HAVING AVG(EMPLOYEES.SALARY) BETWEEN 10500 AND 12500;

-- Questão 20
CREATE OR REPLACE VIEW DEPART_MANAG AS
    SELECT DEPARTMENTS.DEPARTMENT_NAME, COUNT(EMPLOYEES.EMPLOYEE_ID) AS NUM_GERENTES
    FROM HR.EMPLOYEES
    INNER JOIN HR.DEPARTMENTS 
    ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    WHERE EMPLOYEES.JOB_TITLE LIKE '%Manager%'
    GROUP BY DEPARTMENTS.DEPARTMENT_NAME
    HAVING COUNT(EMPLOYEES.EMPLOYEE_ID) > 1;

